### ISSUE TITLE
new device

### ISSUE THREAD

**Issue by GWan1234** [maccoylton/esp-homekit-swb3-powerstrip#1]
Thank you for sharing, gosund also has a socket WP9, do you have any projects about it?

**Comment by maccoylton** [comment]
Sorry no, I do not have one of those .. can yo send me a link to the spec?

**Comment by GWan1234** [comment]
https://www.gosund.com/download/smart_power_strip/135.html

This is the introduction of the product. Compared with other products, it has a few more jacks. 
If you can help with the adaptation, thank you very much.

**Comment by maccoylton** [comment]
It should be possible. there are a few additional GPIO that need to be dealt with, without a unit though I have no way to develop/test that
